### ISSUE TITLE
State persisting

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#10]
Mosto should have Melted status in memory (and update it every second) and also, persist it on a Mongo db to be able to give a fast response in case of a fail/recover situation.  By Melted status I mean: list of clips loaded in Melted, mapping between this clips and Mosto's playlists and clips and which clip is being played and at what frame or second.

**Comment by Lacrymology** [comment]
should I take care of creating and updating this Status, or do you want me to make an API for you to populate every so often?

I could make something that can be instantiated like so:

``` js
self.meltedState = new MeltedState({
  clips: self.getClips,
  currentClip: self.getCurrentClip,
  currentFrames: self.getCurrentFrames,
  // or maybe a more generic
  status: self.getStatus.
});
```

and then `MeltedState` could call it's callbacks and populate it's own structure, and then save it to the database.

I don't totally see the point of this, though. Shouldn't Mosto check melted for it's status? I understand keeping the mapping hash, but not much else, and that can be kept synchronized automatically whenever there's a change. 

Can you clarify the idea?

**Comment by jmrunge** [comment]
We thought it was a good idea to keep the status persisted to be able to
know where exactly was Melted when Mosto got down... And compare to current
status of Melted to take actions in case they are needed.  But I cant think
in this moment what actions should it take.  Like you said, it will read
Melted status directly from Melted and read playlists directly from Mongo
and correct Melted in case it is wrong... I think we should give this issue
the lowest priority right now and discuss it over the list to define if
this will be necessary or not.

2013/3/28 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
OK, you figure this out with @fabriciocosta and @csrocha, I guess. I'll implement it when the time comes

**Comment by jmrunge** [comment]
Sure! Next wednesday we should talk about it. Please Fabricio and Cristian try to think about this.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Changed milestone to Release.

**Comment by Lacrymology** [comment]
I'm not certain we want this anymore. @xaiki said in case of a mosto fail, caspa should know it's down and raise alarms

**Comment by xaiki** [comment]
El lunes, 6 de mayo de 2013, Tomas Neme escribió:

> I'm not certain we want this anymore. @xaiki https://github.com/xaikisaid in case of a mosto fail, caspa should know it's down and raise alarms
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/10#issuecomment-17504956
> .

Yup.

Please focus in testing for these 2 days

## 

Sent from Gmail Mobile

**Comment by jmrunge** [comment]
2013/5/6 Niv Sardi notifications@github.com

> El lunes, 6 de mayo de 2013, Tomas Neme escribió:
> 
> > I'm not certain we want this anymore. @xaiki https://github.com/xaikisaid
> > in case of a mosto fail, caspa should know it's down and raise alarms
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/issues/10#issuecomment-17504956>
> > .
> 
> Yup.
> 
> Please focus in testing for these 2 days

Idem, can you close issue please?
