### ISSUE TITLE
Blank.html has hardcoded path

### ISSUE THREAD

**Issue by josx** [inaes-tic/mbc-mosto#109]
On https://github.com/inaes-tic/mbc-mosto/blob/master/test/videos/blank.xml  you have hardcoded you path.

**Comment by Lacrymology** [comment]
I know. This should not only not be hardcoded, but there also should be some way of defining this either via the settings, or some sort of editor

**Comment by xaiki** [comment]
you should generate these from a setting string and node-mlt.

On 21 June 2013 13:43, Tomas Neme notifications@github.com wrote:

> I know. This should not only not be hardcoded, but there also should be
> some way of defining this either via the settings, or some sort of editor
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/109#issuecomment-19826943
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Well, it is generated via node-mlt to load it into melted, but it is
already an xml and I think it is ok this way for testing.  In production,
users should be able to select a video or image and set filters they would
like to see on top of it.  Im now fixing the hardcoded value inside the xml
and inside models/Mosto.js.

2013/6/26 Niv Sardi notifications@github.com

> you should generate these from a setting string and node-mlt.
>
