### ISSUE TITLE
Mosto <-> Caspa models

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#11]
Mosto is using its own model (Playlist.js and Media.js in /api)  It should start using Caspa's Playlist and Media models to ensure a stright communication between them.

**Comment by Lacrymology** [comment]
I'm not sure I agree. I mean, Caspa playlists right now have a LOT of metadata which I'm not sure matters, and I'd like to keep Mosto's memory usage as controlled as possible.

The mongo-driver does the job of transforming the database documents into mosto's Playlist and Media objects, isn't that good?

Otherwise all of the mosto code using the Playlist and Media objects will have to be fixed

**Comment by jmrunge** [comment]
Well, right now there is no much code using Playlist and Media, so it is the time for defining it.  I like what Tom says... Opinions? (Niv?)

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
I think Playlist and Media should be develop on the "agile" philosophy. This is, the client app (Mosto) should define their interfaces as it finds out what it needs from them, and the drivers should evolve to fill them in.

I trust what is in them now is needed by whatever code uses it. I say let it grow as mosto needs grow, and let the driver grow with it.

**Comment by jmrunge** [comment]
+1.
Niv?

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by xaiki** [comment]
+1 but please keep syntax as close as possible to caspa's
i.e. please leave any field that could be in the model in the same place,
and just trim what comes from caspa to your needs.
that will reduce greatly dev-hate on us.

## 

Niv Sardi

**Comment by Lacrymology** [comment]
hm, Mosto has, e.g., Media.fps while Medias in caspa have Media.video.fps. Is that bad?

**Comment by jmrunge** [comment]
I think not. 

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
in any case, I think mosto's Playlist and Media should match as closely as possible melted's concepts of those, not caspa's. Or at least, represent the data it needs to create them.

With the current drivers architecture, Mosto remains db-format agnostic and only the driver needs to know the format handled by caspa / gstfs.

Of course, I'm all for keeping nomenclature as tight as possible, but from the go Mosto's and Caspa's Playlists are different concepts (Mosto.Playlist = Caspa.Occurrence)

**Comment by jmrunge** [comment]
Ok with this!

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by xaiki** [comment]
+1

## 

Niv Sardi

**Comment by jmrunge** [comment]
Done in #28
