### ISSUE TITLE
Melted clip names

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#12]
Mosto is generating xml to load clips into Melted.  This xml have the name of the clip as file name.  They should be named some way they refer to the playlist id and the clip id for Caspa's driver and the playlist name and the clip name for the Json driver to be able to map them in case Mosto's persisted mapping fails for some reason.

**Comment by xaiki** [comment]
That's quite important.
We need to normaliza that with gstfs

Niv sardi

**Comment by jmrunge** [comment]
Do you mean gstfs should name the files the same way Mosto will do it?  I
think gstfs will know only of "clips", not playlists.  But I may be wrong.
I missed the meeting when you talked about it.  For the moment we should at
least make Mosto do this to be able of rebuild its status when recovering
from a fail.  We should keep it in mind when we start working on gstfs.

2013/3/26 Niv Sardi notifications@github.com

> That's quite important.
> We need to normaliza that with gstfs
> 
> Niv sardi
>

**Comment by jmrunge** [comment]
Fixed in #46
