### ISSUE TITLE
Use mbc-common logging

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#129]
Mosto's logger has been incorporated into mbc-common.  We should remove logger code from mosto and import it from common.

**Comment by josx** [comment]
I have ported mosto logger with some tweaks to mbc-common
Wait until the team finnishs to review and merge PR https://github.com/inaes-tic/mbc-common/pull/18.

**Comment by jmrunge** [comment]
Well, https://github.com/inaes-tic/mbc-common/pull/18 is in, so we can
proceed with this.

2013/9/26 José Luis Di Biase notifications@github.com

**Comment by josx** [comment]
@jmrunge  I can work on that

**Comment by josx** [comment]
@jmrunge  Please check it out on https://github.com/inaes-tic/mbc-mosto/pull/130

**Comment by xaiki** [comment]
#130 merged
