### ISSUE TITLE
Sync/Seek handling

### ISSUE THREAD

**Issue by darthpolly** [inaes-tic/mbc-mosto#133]
I experienced a syncing issue after ~1h of playback. The visual result was that in an interval of ~30secs the actual second of the current clip was reproduced twice, like a 1 second seek backwards.

This might be expected, however i think seeking is not the right way to handle a resynchronization. It is too aggressive, visually speaking, and it feels as if the software were not reproducing properly.

The synchronization should not be detected by the user. Maybe aggregating and syncing at the end of the track?

**Comment by xaiki** [comment]
It's a hard problem, and probably a bug in libmlt.
I don't think we need to fix it in mosto.

On 18 October 2013 19:11, Patricio Reboratti notifications@github.comwrote:

> I experienced a syncing issue after ~1h of playback. The visual result was
> that in an interval of ~30secs the actual second of the current clip was
> reproduced twice, like a 1 second seek backwards.
> 
> This might be expected, however i think seeking is not the right way to
> handle a resynchronization. It is too aggressive, visually speaking, and it
> feels as if the software were not reproducing properly.
> 
> The synchronization should not be detected by the user. Maybe aggregating
> and syncing at the end of the track?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/133
> .

## 

Niv Sardi

**Comment by xaiki** [comment]
(let's find the culprit, and fix/report-it in mlt/melted/...)

On 18 October 2013 22:16, Niv Sardi xaiki@evilgiggle.com wrote:

> It's a hard problem, and probably a bug in libmlt.
> I don't think we need to fix it in mosto.
> 
> On 18 October 2013 19:11, Patricio Reboratti notifications@github.comwrote:
> 
> > I experienced a syncing issue after ~1h of playback. The visual result
> > was that in an interval of ~30secs the actual second of the current clip
> > was reproduced twice, like a 1 second seek backwards.
> > 
> > This might be expected, however i think seeking is not the right way to
> > handle a resynchronization. It is too aggressive, visually speaking, and it
> > feels as if the software were not reproducing properly.
> > 
> > The synchronization should not be detected by the user. Maybe aggregating
> > and syncing at the end of the track?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/133
> > .
> 
> ## 
> 
> Niv Sardi

## 

Niv Sardi

**Comment by Lacrymology** [comment]
I wonder now if this doesn't have to do with the issue we found today about
the difference between DB and melted framerate..

**Comment by Lacrymology** [comment]
having the offending clip to test would be great

**Comment by xaiki** [comment]
if it's fixed by unifying entry, then we don't worry about it.
it'll be fixed when we do the ingester.

On 18 October 2013 22:23, Tomas Neme notifications@github.com wrote:

> having the offending clip to test would be great
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/133#issuecomment-26640416
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
I IMAGINE that's it, but I'm not sure

**Comment by josx** [comment]
In the meantime:
maybe we can add to the scraper a ffmpeg pipeline to force the video fps or whatever we want.

**Comment by xaiki** [comment]
On 19 October 2013 08:44, José Luis Di Biase notifications@github.comwrote:

> In the meantime:
> maybe we can add to the scraper a ffmpeg pipeline to force the video fps
> or whatever we want.

we could, but it's REALLY dangerous, it works only for tests.
I'd rather REJECT and notify when ingesting​​, that will help us set ui
ground work for the injester anyway.

**Comment by jmrunge** [comment]
This should be fixed in last master.  @darthpolly could you check if you
can reproduce now? If not, please close the issue. Thanks.

2013/10/19 Niv Sardi notifications@github.com

**Comment by darthpolly** [comment]
I will check, though we first experienced this issue on @lvidarte 's laptop
so he should check it too before closing the issue.

On Fri, Nov 15, 2013 at 1:10 PM, Juan Martin Runge <notifications@github.com

> wrote:
> 
> This should be fixed in last master. @darthpolly could you check if you
> can reproduce now? If not, please close the issue. Thanks.
> 
> 2013/10/19 Niv Sardi notifications@github.com
> 
> > On 19 October 2013 08:44, José Luis Di Biase notifications@github.comwrote:
> > 
> > > In the meantime:
> > > maybe we can add to the scraper a ffmpeg pipeline to force the video
> > > fps
> > > or whatever we want.
> > 
> > we could, but it's REALLY dangerous, it works only for tests.
> > I'd rather REJECT and notify when ingesting, that will help us set ui
> > ground work for the injester anyway.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/issues/133#issuecomment-26655830>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/133#issuecomment-28580647
> .

## 

DP.-
