### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#15]
We should implement some kind of log for Melted.  We should also clean a bit console.log messages it is writing right now as they are used for debug only.

**Comment by Lacrymology** [comment]
We should move all console.log messages to https://github.com/flatiron/winston

**Comment by Lacrymology** [comment]
https://github.com/inaes-tic/mbc-common/issues/1

**Comment by jmrunge** [comment]
Agree, assigned @csrocha to this issue if it is ok with you.

2013/4/8 Tomas Neme notifications@github.com

**Comment by jmrunge** [comment]
Depends on https://github.com/inaes-tic/mbc-common/issues/1

**Comment by jmrunge** [comment]
@csrocha Any progress with this?

**Comment by jmrunge** [comment]
Closed by #116
