### ISSUE TITLE
Replace mub/sub

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#25]
As Tom find out mub/sub was too slow (til 8 sec of delay) we need to change to a real time pub/sub engine.  Please find and test some, pick one and replace current mub/sub implementation in mongo driver.

**Comment by xaiki** [comment]
redis.

On 3 April 2013 16:04, Juan Martin Runge notifications@github.com wrote:

> As Tom find out mub/sub was too slow (til 8 sec of delay) we need to
> change to a real time pub/sub engine. Please find and test some, pick one
> and replace current mub/sub implementation in mongo driver.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/25
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Please publish current version of driver before starting to work on this
issue and open new branch for it.

2013/4/3 Niv Sardi notifications@github.com

**Comment by Lacrymology** [comment]
Current code can be seen in brach `Lacrymology/playlists/mongo-driver`.

There's a lot of stuff that shouldn't be where it is, like the DB setup and connection code, I'm working on moving that out and cleaning it up

**Comment by jmrunge** [comment]
Ok. Please pull request as soon as you can and then move on to replacing mubsub on a new branch.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Changed milostone to Release.  Please focus on the issues for Malbec Day.

**Comment by Lacrymology** [comment]
done in #90
