### ISSUE TITLE
Move to promises

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#32]
Change mvcp-server invocations from callbacks to promises

**Comment by xaiki** [comment]
this is actually a bigger discution, for further ahead,
callback is an anti-pattern in javascript, we have many options:
- pub/sub (aka, eventEmitter)
- promise|A
- your favourite pattern.

## we should decide on one and move all code to it.

Niv Sardi

**Comment by jmrunge** [comment]
Well, melted-node uses promises with the Q library.  I would continue with
this approach.  But after 17A.  There is much code to migrate right now and
dont want to introduce a stopper feature.

2013/4/8 Niv Sardi notifications@github.com

**Comment by xaiki** [comment]
this is clearly for #sip.

On 8 April 2013 12:01, Juan Martin Runge notifications@github.com wrote:

> Well, melted-node uses promises with the Q library. I would continue with
> this approach. But after 17A. There is much code to migrate right now and
> dont want to introduce a stopper feature.
> 
> 2013/4/8 Niv Sardi notifications@github.com
> 
> > this is actually a bigger discution, for further ahead,
> > callback is an anti-pattern in javascript, we have many options:
> > - pub/sub (aka, eventEmitter)
> > - promise|A
> > - your favourite pattern.
> > 
> > ## we should decide on one and move all code to it.
> > 
> > Niv Sardi
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/issues/32#issuecomment-16055380>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/32#issuecomment-16055529
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
wait, just to clarify:
- the `object.method(param, param2, callback)` pattern is good, for one shots
- the `object.setCallback(callback); object.method(param, param2) // this calls callback` pattern is bad both for one-shots and events
- the `object.on('event', callback)` is ideal for the above situation (by "ideal" I mean "standard". Also I think after 17A we should migrate the playlist driver to this pattern as well)
- I don't know what the promise pattern is. But I think it's for one-shots as well, right? isn't it essentially the same as the first pattern above?

**Comment by xaiki** [comment]
On 8 April 2013 12:58, Niv Sardi xaiki@evilgiggle.com wrote:

> On 8 April 2013 12:53, Tomas Neme notifications@github.com wrote:
> 
> > wait, just to clarify:
> > 
> > the object.method(param, param2, callback) pattern is good, for one shots
> 
> not really, because you end up writting
> object.method (param, param2, function () {
>  object.method2 (param3, function () {
>  ...
> ..
> 
> > the object.setCallback(callback); object.method(param, param2) // this
> > calls callback pattern is bad both for one-shots and events
> > the object.on('event', callback) is ideal for the above situation
> > I don't know what the promise pattern is. But I think it's for one-shots
> > as well, right? isn't it essentially the same as the first pattern above?

promises make you write
object.method(param, param2)
.then().object.method2(param3)
.then().object.method3(param4)
.error(/\* handle errors */)

**Comment by jmrunge** [comment]
You can look at melted-node to see promises in action.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
> not really, because you end up writting object.method (param, param2, function () {
> ...
> object.method2 (param3, function () {
> ...

Well, I don't see this is much of a problem. About 80% of javascript code is that, and for an antipattern, it's pretty descriptive and readable. Besides, it's standard, which is about the second most important thing, right after  [backwards binary compatibility](http://lkml.org/lkml/2012/3/8/495)

**Comment by jmrunge** [comment]
Well, I really thing promised code looks prettier and more easy to
understand than callbacks.  Specially when you have callback from callback
from callback, like you do with melted when trying to do sync commands on
an async language.  And sure does easier error handling.

2013/4/8 Tomas Neme notifications@github.com

**Comment by xaiki** [comment]
let's put this on the agenda for tomorrow.

On 8 April 2013 23:29, Juan Martin Runge notifications@github.com wrote:

> Well, I really thing promised code looks prettier and more easy to
> understand than callbacks. Specially when you have callback from callback
> from callback, like you do with melted when trying to do sync commands on
> an async language. And sure does easier error handling.
> 
> 2013/4/8 Tomas Neme notifications@github.com
> 
> > not really, because you end up writting object.method (param, param2,
> > function () {
> > ...
> > 
> > object.method2 (param3, function () {
> > ...
> > 
> > Well, I don't see this is much of a problem. About 80% of javascript
> > code is that, and for an antipattern, it's pretty descriptive and
> > readable.
> > Besides, it's standard, which is about the second most important thing,
> > right after backwards binary compatibility<
> > http://lkml.org/lkml/2012/3/8/495>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/issues/32#issuecomment-16085345>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/32#issuecomment-16090877
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Ok

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
I just added [a library called async](https://github.com/caolan/async#map) to mosto dependencies. It may help you with "sync"ing things

I used the `async.map(array, iterator, callback)` function that calls your callback with a list of the async results of your iterator function

**Comment by jmrunge** [comment]
Its in agenda for tomorrow

2013/4/9 Tomas Neme notifications@github.com

**Comment by jmrunge** [comment]
Done in backbone refactor.
