### ISSUE TITLE
Add "isConnected" method to mvcp server

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#33]
We should be able to ask mvcp server if it is connected or not.  Right now, the only way of knowing it is hacking down to melted implementation (hakish) or by the connect error handler.  Also it would be nice if this method "pings" mvcp server to be sure it is connected.

**Comment by xaiki** [comment]
On 8 April 2013 14:54, Juan Martin Runge notifications@github.com wrote:

> We should be able to ask mvcp server if it is connected or not. Right now,
> the only way of knowing it is hacking down to melted implementation
> (hakish) or by the connect error handler. Also it would be nice if this
> method "pings" mvcp server to be sure it is connected.
> 
> I'd rather make it a property, or at least a getter method only, and check
> internally if we are connected (with a timeout can be)

## 

Niv Sardi

**Comment by jmrunge** [comment]
Thats what I had in mind.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Kind of this was done in #39.  I will close this issue since Im starting to rewrite melted-node to use connection pool, so it will become useless.

**Comment by jmrunge** [comment]
Closed #33
