### ISSUE TITLE
Silence log on tests

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#34]
Logging on tests should be silenced except for failed tests.

**Comment by Lacrymology** [comment]
this should depend on #15

**Comment by Lacrymology** [comment]
https://github.com/inaes-tic/mbc-common/issues/1

**Comment by jmrunge** [comment]
Sure.

2013/4/8 Tomas Neme notifications@github.com

**Comment by jmrunge** [comment]
Test are silent now.  Despite this, we still have to find a logging facility.
