### ISSUE TITLE
Mosto broken by mongodb install

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#35]
Cant run mosto.  Did npm install.  Failed:

jmrunge@wks-it3-brc:~/mbc/mbc-mosto$ npm install
npm http GET https://registry.npmjs.org/moment/2.0.0
npm http GET https://registry.npmjs.org/mongoskin
npm http 304 https://registry.npmjs.org/mongoskin
npm http 200 https://registry.npmjs.org/moment/2.0.0
npm http GET https://registry.npmjs.org/moment/-/moment-2.0.0.tgz
npm http 200 https://registry.npmjs.org/moment/-/moment-2.0.0.tgz
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/mongodb
npm http 200 https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/redis/-/redis-0.8.2.tgz
npm http 200 https://registry.npmjs.org/redis/-/redis-0.8.2.tgz
npm http 200 https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/bson/0.1.5
npm http 304 https://registry.npmjs.org/bson/0.1.5

> bson@0.1.5 install /home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/node_modules/mongodb/node_modules/bson
> node install.js || (exit 0)
# 

=                                                                              =
=  Attempting to build bson c++ extension                                      =
=   Windows: no build will be attempted as binaries are prepackaged            =
=   Unix: on failure the package will still install without the C++ extension  =
# =                                                                              =

node-gyp clean
make: node-gyp: No se encontró el programa
make: **\* [clean] Error 127
child process exited with code 2
mubsub@0.2.0 ./node_modules/mubsub 
moment@2.0.0 ./node_modules/moment 
mbc-common@0.1.0 ./node_modules/mbc-common 
└── redis@0.8.2
mongoskin@0.4.4 ./node_modules/mongoskin 
└── mongodb@1.1.11
jmrunge@wks-it3-brc:~/mbc/mbc-mosto$

**Comment by jmrunge** [comment]
Tried npm install node-gyp:

jmrunge@wks-it3-brc:~/mbc/mbc-mosto$ npm install node-gyp
npm http GET https://registry.npmjs.org/node-gyp
npm http 200 https://registry.npmjs.org/node-gyp
npm http GET https://registry.npmjs.org/node-gyp/-/node-gyp-0.9.5.tgz
npm http 200 https://registry.npmjs.org/node-gyp/-/node-gyp-0.9.5.tgz
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.0.tgz
npm http 200 https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/osenv/-/osenv-0.0.3.tgz
npm http 200 https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/npmlog/-/npmlog-0.0.2.tgz
npm http 200 https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/fstream/-/fstream-0.1.22.tgz
npm http 200 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/nopt/-/nopt-2.1.1.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.1.4.tgz
npm http 200 https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/which/-/which-1.0.5.tgz
npm http 200 https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/tar/-/tar-0.1.17.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-0.2.11.tgz
npm http 200 https://registry.npmjs.org/osenv/-/osenv-0.0.3.tgz
npm http 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.0.tgz
npm http 200 https://registry.npmjs.org/npmlog/-/npmlog-0.0.2.tgz
npm http 200 https://registry.npmjs.org/fstream/-/fstream-0.1.22.tgz
npm http 200 https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/semver/-/semver-1.1.4.tgz
npm http 200 https://registry.npmjs.org/nopt/-/nopt-2.1.1.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.1.4.tgz
npm http 200 https://registry.npmjs.org/which/-/which-1.0.5.tgz
npm http 200 https://registry.npmjs.org/tar/-/tar-0.1.17.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-0.2.11.tgz
npm http 200 https://registry.npmjs.org/semver/-/semver-1.1.4.tgz
npm http 200 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/glob/-/glob-3.1.21.tgz
npm http 200 https://registry.npmjs.org/glob/-/glob-3.1.21.tgz
npm http 200 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request/-/request-2.16.6.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.16.6.tgz
npm ERR! error installing node-gyp@0.9.5
npm ERR! error rolling back node-gyp@0.9.5 Error: ENOTEMPTY, rmdir '/home/jmrunge/mbc/mbc-mosto/node_modules/node-gyp'

npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: request@2.16.6
npm ERR! Required: ["node >= 0.8.0"]
npm ERR! Actual:   {"npm":"1.1.4","node":"0.6.19"}
npm ERR! 
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-gyp"
npm ERR! cwd /home/jmrunge/mbc/mbc-mosto
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! code ENOTSUP
npm ERR! message Unsupported
npm ERR! errno {}
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/block-stream
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jmrunge/mbc/mbc-mosto/npm-debug.log
npm not ok
jmrunge@wks-it3-brc:~/mbc/mbc-mosto$

**Comment by Lacrymology** [comment]
very weird, this worked for me with node 0.6.x

**Comment by Lacrymology** [comment]
try checking for a version of node-gyp compatible with node 0.6?

**Comment by jmrunge** [comment]
Fixed node-gyp issue.  Had to upgrade to node 0.8.1.  Deleted node_modules/mongoskin and node_modules/mubsub.  Did npm install again. Now without errors.

But when I run "node mosto.js" I get following exception:

TypeError: Cannot read property 'state' of null
    at Connection.disconnected (/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/connection.js:16:22)
    at Promise.Channel.subscribe.handle (/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/channel.js:56:33)
    at Promise.resolve (/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/promise.js:24:18)
    at Object.exports.error (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/utils.js:27:5)
    at EventEmitter.exports.bindSkin.obj.(anonymous function) (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/utils.js:66:17)
    at EventEmitter.g (events.js:185:14)
    at EventEmitter.emit (events.js:91:17)
    at null.<anonymous> (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/db.js:98:22)
    at SkinDb.open (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/db.js:109:11)
    at Db.open (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/db.js:282:16)

What do I need to do to get mosto back working?

**Comment by Lacrymology** [comment]
do you have mongodb installed and running? it seems like you don't

**Comment by xaiki** [comment]
we probably need a better error message here though.

On 9 April 2013 11:57, Tomas Neme notifications@github.com wrote:

> do you have mongodb installed and running? it seems like you don't
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/35#issuecomment-16117595
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Sure I dont. I didnt saw anywhere any message telling that mongodb should be configured or started.  Can you provide instructions?

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by xaiki** [comment]
On 9 April 2013 13:45, Juan Martin Runge notifications@github.com wrote:

> Sure I dont. I didnt saw anywhere any message telling that mongodb should
> be configured or started. Can you provide instructions?

... mubsub == MONGOubsub, you need mongo:

# apt-get install mongodb

## 

Niv Sardi

**Comment by jmrunge** [comment]
Sounds logic... But would be nice to explicit in the commits or in the PR
message what is needed... node 0.8, node-gyp, mongodb.  And how to install
it.  Right now Im downloading mongo.  Will update issue as soon as I get it
running.

2013/4/9 Niv Sardi notifications@github.com

**Comment by jmrunge** [comment]
Well, now I have mongodb installed and running, but still got this error:

mbc-mosto: [INFO] Reading configuration from ./config.json
mbc-mosto: [INFO] Creating server for type [melted]
mbc-mosto: [INFO] Creating server instance [localhost:5250]
mbc-mosto: [INFO] Server instance created [localhost:5250]
mbc-mosto: [INFO] Creating playlists driver for type [mongo]
mbc-mosto: [INFO] Creating mongodb playlists driver
mbc-mosto: [INFO] Starting mbc-mosto... 
mbc-mosto: [INFO] Connecting to server instance [localhost:5250]
melted-node: [connect] Invoked
mbc-mosto: [INFO] Start watching config file ./config.json
mbc-mosto: [INFO] Initializing playlists driver

# mbc-mosto: [INFO] Starting playlists driver

=  Please ensure that you set the default safe variable to one of the                  =
=   allowed values of [true | false | {j:true} | {w:n, wtimeout:n} | {fsync:true}]     =
=   the default value is false which means the driver receives does not                =
=   return the information of the success/error of the insert/update/remove            =
=                                                                                      =
=   ex: new Db(new Server('localhost', 27017), {safe:false})                           =
=                                                                                      =
=   http://www.mongodb.org/display/DOCS/getLastError+Command                           =
=                                                                                      =
=  The default of false will change to true in the near future                         =
=                                                                                      =

# =  This message will disappear when the default safe is set on the driver Db           =

[Error: failed to connect to [localhost:27017]]
melted-node: [connect] Could not connect to Melted Server: Error: connect ECONNREFUSED

/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/connection.js:16
    return this.db.db.state === 'disconnected';
                     ^
TypeError: Cannot read property 'state' of null
    at Connection.disconnected (/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/connection.js:16:22)
    at Promise.Channel.subscribe.handle (/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/channel.js:56:33)
    at Promise.resolve (/home/jmrunge/mbc/mbc-mosto/node_modules/mubsub/lib/promise.js:24:18)
    at Object.exports.error (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/utils.js:27:5)
    at EventEmitter.exports.bindSkin.obj.(anonymous function) (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/utils.js:66:17)
    at EventEmitter.g (events.js:185:14)
    at EventEmitter.emit (events.js:91:17)
    at null.<anonymous> (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/db.js:98:22)
    at SkinDb.open (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/lib/mongoskin/db.js:109:11)
    at Db.open (/home/jmrunge/mbc/mbc-mosto/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/db.js:282:16)

**Comment by jmrunge** [comment]
Was in the first run only... Further runs throwed no errors.  Clues?

**Comment by Lacrymology** [comment]
no clue.. weird but if it keeps working from now on, this should be done

**Comment by jmrunge** [comment]
Closed #35
