### ISSUE TITLE
Migrate playlist driver to EventEmitter

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#41]
We should lose `register[New|Update|Remove]PlaylistListener` methods and make the playlist driver into an `EventEmitter`

**Comment by xaiki** [comment]
done, ain it ?

On 10 April 2013 18:37, Tomas Neme notifications@github.com wrote:

> We should lose register[New|Update|Remove]PlaylistListener methods and
> make the playlist driver into an EventEmitter
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/41
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
As spoken yesterday, Tom will work with this next days...

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
I'll do this tomorrow

**Comment by jmrunge** [comment]
I think this is done in #83 ? Please, @Lacrymology confirm and close if its ok.
