### ISSUE TITLE
Expose new mongo playlist driver functionality on the generic playlist driver

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#44]
And write tests for it. Take them from the `mongo-playlist-driver` test

**Comment by jmrunge** [comment]
This was done in #38 or in #28, doesnt?  If so, please close this issue... Thanks!

**Comment by Lacrymology** [comment]
No, I never got around to the JSON driver!

**Comment by jmrunge** [comment]
Status @Lacrymology ?

**Comment by Lacrymology** [comment]
idem

**Comment by Lacrymology** [comment]
The generic playlist driver doesn't expose any interface now
