### ISSUE TITLE
Caspa Driver

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#5]
We need to implement a Caspa Driver based on the json driver to read the playlists from Caspa's mongo db and receive the notifications from insert/update/delete playlists from Caspa via mub/sub.

**Comment by Lacrymology** [comment]
WIP in https://github.com/inaes-tic/mbc-mosto/blob/Lacrymology/playlists/mongo-driver/drivers/playlists/mongo-driver.js

**Comment by jmrunge** [comment]
Looks promising! I think there are the 'new' playlist notification and
'remove' playlist notifications still missing, arent they?

2013/3/28 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
Yes, there's a problem in caspa's backbone.io notifying, I think it publishes the 'create' message as it receives it, before saving it to the DB. In any case, lacks the _id, which I require here since it's the playlist "name" (which will change to "id" in the near future)

**Comment by jmrunge** [comment]
Sure. I think you already filled an issue on Caspa, right? Please Niv, can you assign somebody to it!

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by xaiki** [comment]
On 29 March 2013 14:56, Juan Martin Runge notifications@github.com wrote:

> Sure. I think you already filled an issue on Caspa, right? Please Niv, can
> you assign somebody to it!

I shall assign, tom to it, as he knows lots about both.
is this a reason to generate our own ids ?
maybe a hash of the sums of the elements ?

maybe generate it in the middleware (it'll then go back to mongo with it,

## and back up via backbone.io)

Niv Sardi

**Comment by Lacrymology** [comment]
This is better discussed in it's issue https://github.com/inaes-tic/mbc-playout/issues/52

I have the feeling the ideal would be making a backbone.io connection from mosto to caspa, but Niv said he'd had problems with that

**Comment by jmrunge** [comment]
Ok! Tom: you are the man! :)

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Mmm. I would prefer keep Mosto out of backbone.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
you mean backbone out of mosto?

Yeah, probably. I also have the feeling that linking through backbone.io would make it hard to keep track of memory usage. Right now I just load the db objects (which may become big, specially if there's a lot of short media), load a fraction of the contents into Mosto.Playlist and Mosto.Media, and dismiss it (I can trust the garbage collector, right?)

**Comment by jmrunge** [comment]
I think you can trust gc, but we should make some stress tests to be sure.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by xaiki** [comment]
the problem is this:
- if you connect dirrectly backbone.io (I.e. via websockets) you break a
  design rule: mosto and caspa should exist independently.
- if you connect via pubsub (i.e. pushing the pubsub messages back to a new
  backbone.io) you only use a part of backbone.io (the backend) and have lots
  of code that is there to work with the frontend that is useless.

anyway, if we don't violate objects ownership, we shouldn't need any of
this.

what we loose, not using backbone, is that we need to ORM, i.e. find a way
to describe what has changed in the objects we move.
but we can use the hints backbone is giving us.

## 

Niv Sardi

**Comment by jmrunge** [comment]
I think its the best way: pub/sub without backbone and describing the most possible what changed...

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
I say we move this talk to a live meeting.

**Comment by jmrunge** [comment]
Ok! Can it be wednesday morning? Or after lunch (14 hs)?

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by xaiki** [comment]
On 1 April 2013 10:22, Juan Martin Runge notifications@github.com wrote:

> Ok! Can it be wednesday morning? Or after lunch (14 hs)?

we shall all be together from morning.
I think fabricio's TZ prefers 14h though.

**Comment by jmrunge** [comment]
14 hs then. Ok?
Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Fixed by #28
