### ISSUE TITLE
Test playlist driver setWindow parameters

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#50]
More comprehensive testing on the `setWindow` parameters should be implemented.

There's some difficulty on testing stuff that assume `now` and calculate it on the fly

**Comment by jmrunge** [comment]
I would prefer to use setTimeSpan method.  But both should be well tested.

**Comment by Lacrymology** [comment]
`mongo_driver.prototype.setTimeSpan = function(timespan) { this.setWindow({span: timespan}) }`

not much to test there

**Comment by jmrunge** [comment]
Ok! and setWindow? Is it still alive?

2013/4/15 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
As Far As I Can See, there's no `setTimeSpan` function at all, I was just saying that if we write it, that would be it.

the functionality you want right now is achieved by `.setWindow({span: x})`, but I can make the setTimeSpan utility function if you want.

In any case, it'll be @fabriciocosta using it

**Comment by jmrunge** [comment]
Let it be by now... Just wondering if it was tested, due to this issue you
setted up...

2013/4/16 Tomas Neme notifications@github.com

**Comment by jmrunge** [comment]
Just one doubt... Is it tested or not finally this functionality?

**Comment by Lacrymology** [comment]
no, not completely. I do trust the function, thought

**Comment by jmrunge** [comment]
Ok. Please try to test it more and let me know. Thanks!

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
Status @Lacrymology ?

**Comment by fabriciocosta** [comment]
It works for me, as mosto makes the (from,to) window advance. I need to test it more, with smaller and bigger timespans.

**Comment by Lacrymology** [comment]
"works for me" is not an answer.

We need mocha tests

**Comment by Lacrymology** [comment]
not closed

**Comment by Lacrymology** [comment]
#99

**Comment by jmrunge** [comment]
Mongo driver setWindow function was dropped.  Now mosto controls this behaviour.
