### ISSUE TITLE
Mosto must start, stop and setup Melted

### ISSUE THREAD

**Issue by csrocha** [inaes-tic/mbc-mosto#55]
Yes, indeed we need to setup the root to melted if we will be using
relative paths.  I've thought that melted init should be ouside mosto, but
we can have it inside it.  What about an init script that mosto could run?
This script should do only one thing: Start melted.  And it should be
runned from the error handler in mosto that handles mvcp connection error.
It can be a single command line in mosto config too.  Then, set up root.
After, we should ask for ULS.  If U0 is not present, we should create it.
What type of unit should be in config too (sdl, decklink, bluefish,
avformat, etc).  I can implement ULS in mvcp driver.  And shutdown too.
This way, in tests we could:
- Shutdown melted
- Start it
- Set root
- Add unit
- Start all tests

**Comment by jmrunge** [comment]
I think this should be part of the mvcp driver.  And be in mvcp driver config file.  An init script that kills and restarts melted.  And units (and consumers for each unit) to add (I think in the future we may have more than one unit, ie: deckling for air and avformat for streaming).  Im planning to add server methods to mvcp driver (ULS, SET, GET, etc) after Malbec Day.  Will fill an issue with mvcp server methods.

**Comment by xaiki** [comment]
for now it'd be nice to push this for malbecday.
@csrocha had some code working arround this lane.

**Comment by jmrunge** [comment]
Will be glad to do it!

2013/4/24 Niv Sardi notifications@github.com

**Comment by jmrunge** [comment]
Closed with restart by #115
