### ISSUE TITLE
Should the status driver setup a "mosto down" status at startup?

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#56]
Should an "alert" type status be set up at status driver intiialization, to be kept until the next status update comes? I realized using the last saved status is not very.. professional? realistic?

**Comment by jmrunge** [comment]
I think we cant use the last saved status... But am not sure if there should be an "alert" status... Absence of status wont be enough? From Caspa side: "no status". Just thinking...

**Comment by jmrunge** [comment]
Status emitter (#63) does something like this, sending everything as undefined except for melted status: stopped.

**Comment by jmrunge** [comment]
Any new thought about this? @Lacrymology @xaiki @fabriciocosta ?

**Comment by xaiki** [comment]
no we don't.
logic goes like this.
caspa gets info from pub sub.
but times the 'tick' status.
if no tick, mosto is down.
we don't need to actively take care of this in mosto.

On 23 April 2013 11:28, Juan Martin Runge notifications@github.com wrote:

> Any new thought about this? @Lacrymology https://github.com/Lacrymology
> @xaiki https://github.com/xaiki @fabriciocostahttps://github.com/fabriciocosta?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/56#issuecomment-16861327
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
ok, but note:

this is for between mosto startup, and playlists setup.

I'm good with this solution, but please open an issue in caspa for it

**Comment by xaiki** [comment]
(I'm not paid for this, just an open source enthusiast  :-)  please open a
caspa issue for this)

**Comment by Lacrymology** [comment]
=)

you're right, sorry
