### ISSUE TITLE
Playlists sync with melted

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#6]
For the moment, Playlists are loaded in melted and then never updated.  Only new playlists get loaded.  Mosto should check Melted status when receives an update or delete notification from the driver and modify Melted playlists accordingly.

**Comment by jmrunge** [comment]
I think this is done in #74 .  @fabriciocosta ?

**Comment by fabriciocosta** [comment]
Yes it's done and works well for creates and updates, but i fixed already bugs for update>remove playlists. I'm posting an issue on this and the fix too. Something i would like to comment on caspa: i didnt receive any notice nor event when the clips of a playlist has updated in caspa. I'm testing it again, maybe it is already fixed.

**Comment by xaiki** [comment]
@fabriciocosta
fixed -> close + commithash

On 23 April 2013 13:07, Fabricio Costa Alisedo notifications@github.comwrote:

> Yes it's done and works well for creates and updates, but i fixed already
> bugs for update>remove playlists. I'm posting an issue on this and the fix
> too. Something i would like to comment on caspa: i didnt receive any notice
> nor event when the clips of a playlist has updated in caspa. I'm testing it
> again, maybe it is already fixed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/6#issuecomment-16868090
> .

## 

Niv Sardi
