### ISSUE TITLE
Problems with async tests

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#68]
Tests seem to be running in parallel, and many tests conflict with each other.

Something should be done about this ASAP

**Comment by jmrunge** [comment]
@csroca was trying to fix this

2013/4/18 Tomas Neme notifications@github.com

**Comment by xaiki** [comment]
@csrocha any news ?

On 18 April 2013 14:35, Juan Martin Runge notifications@github.com wrote:

> @csroca was trying to fix this
> 
> 2013/4/18 Tomas Neme notifications@github.com
> 
> > Tests seem to be running in parallel, and many tests conflict with each
> > other.
> > 
> > Something should be done about this ASAP
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/issues/68>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/68#issuecomment-16591032
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Nodeunit says it runs serial... Perhaps give it a try?

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
The people on the mocha mailing list assure me it runs serially as well, I think we need to make sure this is our problem.

**Comment by Lacrymology** [comment]
I have the theory that not deleting the objects created for tests might be the source of some of our testing headaches

**Comment by jmrunge** [comment]
This was fixed with Melted api object, using a semaphore.
