### ISSUE TITLE
Review BlackMedia creation

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#73]
We should be sure we always create Blackmedia the same way, I believe a helper function would suffice.

**Comment by xaiki** [comment]
nope, it should come from the config.
and be changeable.

On 19 April 2013 11:53, Juan Martin Runge notifications@github.com wrote:

> We should be sure we always create Blackmedia the same way, I believe a
> helper function would suffice.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/73
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
Sure, the clip does comes from config, but I ment the way it is created...

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by fabriciocosta** [comment]
The creation of BlackMedia or BlankMedia could be placed in utils? Also self.config.black must be renamed as self.config.blank .
Well, we need to discuss a little more about this, because if we use a clip we must define the behavior we want first. If blank is a clip we need to set "in" and "out" parameters to control clip length. I'm checking any loop options in melted. So a standard solution will be to have a 1 second clip loop, a 5 seconds clip loop, or a 1 minute clip loop. Just brainstorming.

**Comment by xaiki** [comment]
On 24 April 2013 11:53, Fabricio Costa Alisedo notifications@github.comwrote:

> The creation of BlackMedia or BlankMedia could be placed in utils? Also
> self.config.black must be renamed as self.config.blank .
> Well, we need to discuss a little more about this, because if we use a
> clip we must define the behavior we want first. If blank is a clip we need
> to set "in" and "out" parameters to control clip length. I'm checking any
> loop options in melted. So a standard solution will be to have a 1 second
> clip loop, a 5 seconds clip loop, or a 1 minute clip loop. Just
> brainstorming.

I think we should use a node-mlt compatible structure.
and default to an animated version of our Malbec logo.

using it that way, we then would need a small editor in Caspa,
but at least we can edit the string in the config straight away.

**Comment by jmrunge** [comment]
For the moment, can we at least change the image to Malbec's logo or a color bar image?  Its quite confusing if we have a black image, we dont know if it is showing or not.

**Comment by Lacrymology** [comment]
This is fixed. It's handled by the Mosto.MeltedCollection Backbone collection now. A new issue should be open to allow creation of a long blank clip by joining several blank tracks.

**Comment by jmrunge** [comment]
Please create the issue then.

-----Original Message-----

**Comment by Lacrymology** [comment]
it already was there: #108
