### ISSUE TITLE
Always doing a loadClip... we need a full StatusMelted

### ISSUE THREAD

**Issue by fabriciocosta** [inaes-tic/mbc-mosto#76]
I can see a blank image between each clip! We are doing loadClip because we need the relative timer clock, but it doesn't work. Why? Because we need a StatusMelted with frame accurate info and length.

**Comment by jmrunge** [comment]
Its done in PR #86 Please review and merge to get this resolved.

**Comment by jmrunge** [comment]
PR #86 is merged into master.  Please take care of this issue ASAP.

**Comment by fabriciocosta** [comment]
Ok, it's done. Check pull request #88 .
