### ISSUE TITLE
Use the goto command to position the expected clip with frame accuracy

### ISSUE THREAD

**Issue by fabriciocosta** [inaes-tic/mbc-mosto#78]
Important when we have for example a 2 hours movie and we need to restart mosto. Mosto must position the clip in the expected frame.

**Comment by xaiki** [comment]
this is fixed here:
https://github.com/inaes-tic/mbc-mosto/blob/xaiki/wip/mosto.js#L139

**Comment by jmrunge** [comment]
Status @fabriciocosta ?

**Comment by jmrunge** [comment]
Will it be fixed in #88?

**Comment by fabriciocosta** [comment]
Yes i will change my commits to close this issue as well.
