### ISSUE TITLE
Status , fix the send status for caspa.

### ISSUE THREAD

**Issue by fabriciocosta** [inaes-tic/mbc-mosto#79]

**Comment by jmrunge** [comment]
Could we have a description for this @fabriciocosta ?

**Comment by Lacrymology** [comment]
I think this is fixed now, with  #81 and https://github.com/inaes-tic/mbc-caspa/pull/119

**Comment by jmrunge** [comment]
Can you confirm please so we can close issue?

2013/4/23 Tomas Neme notifications@github.com
