### ISSUE TITLE
Pub/Sub Notifications

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#8]
Mosto should implement a pub/sub driver for emitting notifications and receiving requests.  It should be done using mub/sub.  For the moment, it should send its status every second and be able to respond to status and list requests.  Also it should send warning and error messages.

**Comment by xaiki** [comment]
There are many objects, some to update more often than others.
Maybe we only need to be reactive ?

Niv sardi

**Comment by jmrunge** [comment]
Well, I thought Caspa would suscribe to "status" notifications and update
its gui when it receives something.  Thats why I thought Mosto should send
it status every second.  But if you think its better just to send responses
when queried, we can go with it.  Its just a matter of how will Caspa
implement its "live" monitoring gui.

2013/3/26 Niv Sardi notifications@github.com

> There are many objects, some to update more often than others.
> Maybe we only need to be reactive ?
> 
> Niv sardi
>

**Comment by xaiki** [comment]
yep. define that with tomas.

On 26 March 2013 23:54, jmrunge notifications@github.com wrote:

> Well, I thought Caspa would suscribe to "status" notifications and update
> its gui when it receives something. Thats why I thought Mosto should send
> it status every second. But if you think its better just to send responses
> when queried, we can go with it. Its just a matter of how will Caspa
> implement its "live" monitoring gui.
> 
> 2013/3/26 Niv Sardi notifications@github.com
> 
> > There are many objects, some to update more often than others.
> > Maybe we only need to be reactive ?
> > 
> > Niv sardi
> > 
> > El 26/03/2013, a las 08:01, jmrunge notifications@github.com
> > escribió:
> > 
> > > Mosto should implement a pub/sub driver for emitting notifications and
> > > receiving requests. It should be done using mub/sub. For the moment, it
> > > should send its status every second and be able to respond to status and
> > > list requests.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/issues/8#issuecomment-15493061>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/8#issuecomment-15501613
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
I agree with @jmrunge, mosto should push it's updates.

a (very basic) implementation of the playlist updates is already in place in my working branch, it's a lovely one-liner: https://github.com/inaes-tic/mbc-mosto/blob/Lacrymology/playlists/mongo-driver/drivers/playlists/mongo-driver.js#L26

**Comment by jmrunge** [comment]
Well, we are all ok then.  What I would like is that Mosto's status updates
were done outside Mongo's driver.  Ideally, it should implement a kind of
generic pub/sub driver (like we done with playlist-driver) and then a
mub/sub driver that is called from it.  So, later, we could write some
other kind of pub/sub driver (net?) without having to change the rest of
the code.

2013/3/28 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
no, of course. A lot of the code I'm showed will probably have to be moved as well, and the status reports have nothing to do with playlists at all, so it's obvious that can't live within the mongo driver (which's full name would be mongo **playlist** driver)

**Comment by jmrunge** [comment]
Ok! As for the name, it lives inside the playlists dir, so I think is ok just to name it mongo-driver.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by jmrunge** [comment]
@Lacrymology I think this is done already, doesnt it?

**Comment by Lacrymology** [comment]
yes
