### ISSUE TITLE
playlist ids are ints not strings

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#80]
We're having a problem here. ping @fabriciocosta and @jmrunge 

The status driver is returning playlists ids as strings. This means that [this code](https://github.com/inaes-tic/mbc-mosto/blob/master/mosto.js#L380) never tests true, and that the code below doesn't even work right, returns different things depending on the state, but `i` ends up always as `self.playlists.length`, previous is whatever the last playlist is, and next is empty.

Possible solutions include:
- fix melted driver to convert to int. I don't like this because it becomes very coupled with caspa
- fix caspa so it casts to string before saving. Possibly the best solution
- fix the caspa playlists driver to cast to string before returning the `Playlist` objects. Also fix the status driver so it casts back to int before posting the status. I don't like this because it requires fixing two spots.

**Comment by Lacrymology** [comment]
I made the caspa fix, and it works

**Comment by Lacrymology** [comment]
Still, @fabriciocosta should check that code, because if no playlist matches in `self.playlists`, previous and next will be broken

**Comment by jmrunge** [comment]
Broken or undefiend? They should be undefined and a BIG WARNING :)

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
The code is broken, i.e.: it returns the very last clip in the loaded playlists as "previous" whatever it is, and next as undefined, when the "current" id doesn't match any loaded playlists

**Comment by jmrunge** [comment]
Ok. First, this shoul never happend! And second, if it does happen, it should be taken care of.

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
I can imagine a couple of moments when this could happen. When mosto
restarts after a breakdown, if melted´s still running, this might happen at
some point, if at any point the status is brought before playlists are
loaded.

The strings-only thing is also important, because otherwise, if mosto
handles this (by, for example, overriding the playlist melted says to be
playing with it's own), a loop could happen where mosto sees playlist
123456 as current playlist, and tries to reload it when it sees that melted
is running "123456" instead.

**Comment by jmrunge** [comment]
As talked by chat, this should be resolved by using toString() in every comparission, even with Caspa's fix.  Please @fabriciocosta take care of this.

**Comment by Lacrymology** [comment]
I'll do it myself

**Comment by jmrunge** [comment]
Ok, as you wish.

2013/4/23 Tomas Neme notifications@github.com
