### ISSUE TITLE
node server tests don't pass

### ISSUE THREAD

**Issue by Lacrymology** [inaes-tic/mbc-mosto#82]
I think there were some assumptions about startup in mvcp-server-tests that @jmrunge was making in his tests that don't hold anymore, or something.

Please check and fix the tests.

**Comment by jmrunge** [comment]
Well, they do pass in master... Could you give more details?

**Comment by Lacrymology** [comment]
we'll wait for @csrocha's tests fixes

**Comment by jmrunge** [comment]
Assigned to @csrocha
