### ISSUE TITLE
Error: global leaks detected: sched_clip, ex_start, ex_end, playlist

### ISSUE THREAD

**Issue by csrocha** [inaes-tic/mbc-mosto#84]
Los test de mosto declaran este error porque no se ha instanciado localmente o globalmente estas variables. Esto ocurre en mosto.js.

**Comment by jmrunge** [comment]
It will get fixed when #86 gets merged.

**Comment by jmrunge** [comment]
Fixed by #86

**Comment by jmrunge** [comment]
Closed #84
