### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#9]
Mosto should be polling its own playlists list and Melted status to be sure that there is allways 4 hs of clips loaded into melted.

**Comment by jmrunge** [comment]
I think this is done in #74 .  Can you confirm @fabriciocosta ?

**Comment by fabriciocosta** [comment]
Im checking everything right now.

**Comment by fabriciocosta** [comment]
Yes, it is supposed to work like that. I need to put that 4 hours span in the config now. There's another span for the scheduled clips, each hour it checks for new playlist himself completing the 4 hours time window. That should be in the config too. I'm testing this as we speak.

**Comment by xaiki** [comment]
@fabriciocosta
if it's fixed close the bug refering to the commit that closes it.

On 23 April 2013 13:04, Fabricio Costa Alisedo notifications@github.comwrote:

> Yes, it is supposed to work like that. I need to put that 4 hours span in
> the config now. There's another span for the scheduled clips, each hour it
> checks for new playlist himself completing the 4 hours time window. That
> should be in the config too. I'm testing this as we speak.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/9#issuecomment-16867870
> .

## 

Niv Sardi
