### ISSUE TITLE
mosto should detect wrong frame and jump.

### ISSUE THREAD

**Issue by xaiki** [inaes-tic/mbc-mosto#97]
mosto should detect that we are not playing the frame we're supposed to be playing and jump to it.

if for instance you drag a playlist in caspa and move it up/down 1 min, mosto should switch frames.

**Comment by Lacrymology** [comment]
I see that behavior (moving the playlist)

**Comment by Lacrymology** [comment]
ok, no I don't I was seeing it change clips.

**Comment by xaiki** [comment]
I'm talking about frames.
if you move a clip 5mins, it should seek.

we need to be frame perfect.

On 30 April 2013 20:51, Tomas Neme notifications@github.com wrote:

> ok, no I don't I was seeing it change clips.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/97#issuecomment-17261487
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
here's some working code https://github.com/inaes-tic/mbc-mosto/compare/Lacrymology;jump-to-frame

by no means production-grade

**Comment by xaiki** [comment]
https://github.com/inaes-tic/mbc-mosto/commit/1f84d08983e9eba08193ae2dcff84d0628d866e8

this looks quite nicer.
anyway, something much more than this is needed.
and something much less hackish.

On 1 May 2013 11:10, Tomas Neme notifications@github.com wrote:

> here's some working code
> https://github.com/inaes-tic/mbc-mosto/compare/Lacrymology;jump-to-frame
> 
> by no means production-grade
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/97#issuecomment-17283050
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
that code doesn't seem to work, it compares clip time with playlist time, and I don't think it's quite as simple as that anyways. AFAIK, the melted driver doesn't keep playlists, just clips.

I don't think my code is particularily hackish it compares current frame with expected, and if there's a difference, it calls goto, what's hackish about that?

Maybe the used instance variables are a little hackish, but I just used what's already there.

In any case I didn't write the code as a fix, just as an example of the general shape of the thing. It lacks any error handling, to begin with.

**Comment by xaiki** [comment]
it'd just need a cumulative.

On 1 May 2013 18:24, Tomas Neme notifications@github.com wrote:

> that code doesn't seem to work, it compares clip time with playlist time,
> and I don't think it's quite as simple as that anyways. AFAIK, the melted
> driver doesn't keep playlists, just clips.
> 
> I don't think my code is particularily hackish it compares current frame
> with expected, and if there's a difference, it calls goto, what's hackish
> about that?
> 
> Maybe the used instance variables are a little hackish, but I just used
> what's already there.
> 
> In any case I didn't write the code as a fix, just as an example of the
> general shape of the thing. It lacks any error handling, to begin with.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/97#issuecomment-17307462
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
that's what `utils.getFramePositionFromClock( current_time, clip_start, clip_length, fps )` does.

**Comment by Lacrymology** [comment]
I mean, we **know** at what time the current clip was supposed to start, what's the point of falling back to the playlist?

**Comment by Lacrymology** [comment]
oops, missclick

**Comment by xaiki** [comment]
...
this code looks ugly.
if we're in playing, we shouldn't check we're playing.
anyway, leave it for after refactor.

**Comment by Lacrymology** [comment]
Yep, you just don't understand my code and criticize it. That check for if we're playing isn't even part of my patch.

I just added a check for current vs expected frame, and a jump into the current code, and used the data that's already been harvested. I offered an example patch that works with the current codebase, and you showed some code that has nowhere to be put into.

So if what you want to do is a full refactor of the mosto code, say **that**.

**Comment by Lacrymology** [comment]
What I mean is, I offered a fix to the current code that fixes this issue (clarifying that it's by NO MEANS a full solution, but just some code skeleton), and you say "it's ugly" and present some code that not only would NOT work, but it's not even based on a working version of the software.

It's pretty unnerving, to be perfectly sincere

**Comment by xaiki** [comment]
El viernes, 3 de mayo de 2013, Tomas Neme escribió:

> Yep, you just don't understand my code and criticize it.
> 
> Lol
> Reality check
> I'm not going to accept ñor reply to this kind of tone.
> 
>  That check for if we're playing isn't even part of my patch.
> 
> I just added a check for current vs expected frame, and a jump to the
> current code, and used the data that's already been harvested. I offered an
> example patch that works with the current codebase, and you showed some
> code that has nowhere to be put into.
> 
> So if what you want to do is a full refactor of the mosto code, say _that_
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/97#issuecomment-17400176
> .

## 

Sent from Gmail Mobile

**Comment by Lacrymology** [comment]
but I need to accept "this code is ugly"? What am I supposed to understand
if you say my code is ugly and your argument is something that, I repeat,
is not even part of my patch? And your proposed solution doesn't even work.
I'm sorry, you're the one being disrepectful here

**Comment by xaiki** [comment]
El sábado, 4 de mayo de 2013, Tomas Neme escribió:

> but I need to accept "this code is ugly"?

Look at it.
It is. And you know it. No as hominem in that
It's the wrong Place to do this, done the wrong way. On code we agreed to
refactor. Out of your priorities.

> What am I supposed to understand
> if you say my code is ugly

That you should not do it this way.
And that I trust you and expect you to write better code.

> and your argument is something that, I repeat,
> is not even part of my patch? And your proposed solution doesn't even work.
> I'm sorry, you're the one being disrepectful here

 You're obviously mixing things and are far too emotional to resolve this
here
Drop it, we'll talk it on Monday

> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/97#issuecomment-17438222
> .

## 

Sent from Gmail Mobile

**Comment by jmrunge** [comment]
Fixed after backbone refactor.
